### ISSUE TITLE
Location - implement room tour videos

### ISSUE THREAD

**Issue by richardbporter** [ITS-UofIowa/housing.uiowa.edu#12]

**Comment by adamdelaney** [comment]
We need to know where these videos go in the site. Also where are currently are these videos (youtube)?

**Comment by richardbporter** [comment]
Mayflower: https://youtu.be/M25w1twWnhk
Slater: https://youtu.be/wKrT-yItQeg
Burge: https://youtu.be/1r7lmzziMG8
Daum: https://youtu.be/dc9LXZohWBg
Currier: https://youtu.be/sdMYZE8VK_4
Hillcrest: https://youtu.be/Sp4_3jQW5Xc
Petersen: https://youtu.be/mHra8pY0_tU
Rienow: https://youtu.be/KSBWs9l-M7g
On Campus Apartments: https://youtu.be/tB3fsS2tb8I

**Comment by richardbporter** [comment]
I think this is basically done.
