### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by richardbporter** [ITS-UofIowa/housing.uiowa.edu#20]
> We would like the homepage to look like the attached document if possible. This would include a static photo, and three 'card sections' at the bottom to feature items like news, important dates, and a 'work for us' section. We would like to be able to have these cards linkable to a basic page with more information. Also we would like to have a 'Quick Links' section with an 'Apply' and 'Residence Halls.' This would allow the user to quickly access what they are looking for. 

> Lastly, for the 'My Housing' menu, we would like to have it use the cards like we discussed yesterday. Here is an attached photo of what we were thinking it would look like with the cards. 

![cards section](https://user-images.githubusercontent.com/1068523/27341935-551b36b2-55a4-11e7-88bd-6f5e2d1a85d3.png)
[Home Page (Housing Website).docx](https://github.com/ITS-UofIowa/housing.uiowa.edu/files/1088731/Home.Page.Housing.Website.docx)

**Comment by adamdelaney** [comment]
This will be implemented using sitenow_paragraphs and possibly some custom paragraph bundles we build for housing.

**Comment by richardbporter** [comment]
@adamdelaney I finished the upcoming dates block. We can "place it" later I guess via Paragraphs. I manually placed it on the front page for now: https://housing.dev.drupal.uiowa.edu

**Comment by richardbporter** [comment]
I think SNP will allow the homepage to be built with the given requirements.
